AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EnvName:
    Type: String
    Description: Name of an environment. 'dev', 'staging', 'prod' and any name.
    Default: "dev"
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.
Outputs:
  LambdaRoleARN:
    Description: Role for Lambda execution.
    Value:
      Fn::GetAtt:
        - LambdaRole
        - Arn
    Export:
      Name:
        Fn::Sub: LambdaRole
  LambdaFunctionName:
    Value:
      Ref: LambdaFunction
  LambdaFunctionARN:
    Description: Lambda function ARN.
    Value:
      Fn::GetAtt:
        - LambdaFunction
        - Arn
    Export:
      Name:
        Fn::Sub: LambdaARN-${EnvName}
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: form-mailer-lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: form-mailer-${EnvName}
      Handler: index.handler
      Code:
        ZipFile: !Sub |
          var AWS = require('aws-sdk');
          var ses = new AWS.SES();

          var RECEIVER = 'mail@calvinthanh.com';
          var SENDER = 'mail@calvinthanh.com';

          var response = require('cfn-response');

          exports.handler = function(event, context) {
              console.log('Received event:', event);
            
              sendEmail(event, function (err, data) {
                  context.done(err, null);
                  if(err){
                      return err;
                  }
                
              });
          };
          function sendEmail (event, done) {
              console.log(event)
              var params = {
                  Destination: {
                      ToAddresses: [
                          RECEIVER
                      ]
                  },
                  Message: {
                      Body: {
                          Text: {
                              Data: 'name:\t' + event.name + '\nemail:\t' + event.email + '\nmessage:\n' + event.message,
                              Charset: 'UTF-8'
                          }
                      },
                      Subject: {
                          Data: 'Website Referral Form: ' + event.name,
                          Charset: 'UTF-8'
                      }
                  },
                  Source: SENDER
              };
              ses.sendEmail(params, done);
          }
      Runtime: nodejs16.x
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn
